config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root "products#index"

  get "dashboard", to: "dashboards#dashboard"
  get "dashboard/sent", to: "dashboards#sent"
  patch "dashboard/:id/accepted_offer", to: "dashboards#accepted_offer", as: "accepted"
  patch "dashboard/:id/declined_offer", to: "dashboards#declined_offer", as: "declined"
  get "dashboard/received", to: "dashboards#received"
  get "dashboard/finished", to: "dashboards#finished"
  post "dashboard/offer/createCounterOffer", to: "offers#create_counter_offer", as: "counter_offer"

  get "/profile", to: "profiles#profile", as: :my_profile
  patch "/profile", to: "profiles#update", as: :profile

  delete "/product_wishlists/:id", to: "product_wishlists#unheart_wishlist_product", as: :unheart_wishlist_product

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :product_wishlists, only: [:create]
    resources :offers, only: [:create]
  end

  resources :offer_products, only: [:index]
  resources :messages, only: [:index, :show, :new, :create, :destroy]
  resources :offers, only: [:index, :show, :destroy]
  resources :profiles, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :categories, only: [:index]
  resources :product_wishlists, only: [:destroy]
  resources :wishlists, only: [:show]

  resources :products do
    post 'toggle_favorite', on: :member
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def profile
    @user = current_user
    @products = @user.products
  end

  def edit
    @user = User.find(params[:id])
    @categories = Category.new
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to profile_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :address)
  end
end

app/views/profiles/edit.html.erb
<div class="login-container">
  <div class="login-box">
    <%= simple_form_for(@user, url: profile_path, method: :patch) do |f| %>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :bio %>
      <%= f.input :address %>
      <div class="d-flex justify-content-center">
        <%= f.submit "Update", class: "update-button" %>
        <button class="cancel-button" onclick="window.location.href='/profile'; return false;">Cancel</button>
      </div>
    <% end %>
  </div>
</div>
<%= link_to products_path, class: 'btn btn-link' do %>
  <svg class="close-button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40">
    <defs>
      <style>
        .cls-1 {
          fill: #000;
          stroke-width: 0px;
        }

        .cls-2 {
          fill: none;
          stroke: #000;
          stroke-linecap: round;
          stroke-miterlimit: 10;
          stroke-width: 2px;
        }
      </style>
    </defs>
    <g id="Layer_1-2" data-name="Layer 1">
      <g id="nav-bar">
        <g id="btn_edit" data-name="btn edit">
          <path class="cls-1" d="M20,2c9.93,0,18,8.07,18,18s-8.07,18-18,18S2,29.93,2,20,10.07,2,20,2M20,0C8.95,0,0,8.95,0,20s8.95,20,20,20,20-8.95,20-20S31.05,0,20,0h0Z"/>
          <line class="cls-2" x1="11.36" y1="11.37" x2="28.44" y2="28.57"/>
          <line class="cls-2" x1="28.5" y1="11.43" x2="11.3" y2="28.51"/>
        </g>
      </g>
    </g>
  </svg>
<% end %>

app/views/profiles/profile.html.erb
<div class="container-full">
  <div class="d-flex justify-content-center align-items-center mb-30">
    <div>
      <img src="<%= current_user.avatar %>" alt="Profile Picture" class="profile-picture">
    </div>
    <div>
      <%= link_to image_tag("icons/btn profile_edit.svg", style: "width: 25px"), edit_profile_path(current_user) %>
      <%= link_to image_tag("icons/btn logout.svg", style: "width: 25px"), destroy_user_session_path, data: { turbo_method: :delete } %>
    </div>
  </div>
  <div class="container-greetings">
    <h1>Good Morning, <%= current_user.first_name %>! ☀️</h1>
  </div>
  <div class="container-bio mb-3">
    <h3>About me:</h3>
    <p><%= current_user.bio %></p>
      <div class="my-items">
        <h3>MY ITEMS</h3>
      </div>
  </div>
  <div class="profile-product-container">
  <% if @user.products.any? %>
    <% @products.each do |product| %>
      <div class="profile-product-card">
        <div class="profile-product-image product-background">
          <%= cl_image_tag product.photo.key, class: 'product-image img-fluid' %>
        </div>
        <div class="profile-product-info">
          <div class="product-title-container">
            <span class="profile-product-title"><%= truncate(product.title, length: 30, omission: "...") %></span>
          </div>
          <div class="product-description-container">
            <span class="profile-product-description"><%= truncate(product.description, length: 80, omission: "...") %></span>
          </div>
          <div class="profile-product-actions">
            <div class="profile-product-edit-button">
              <%= link_to "Edit", edit_product_path(product), class: "user-button" %>
            </div>
            <div class="profile-product-delete-button">
              <%= link_to image_tag("icons/btn Trash.svg", style: "width: 25px"), product_path(product.id), data: { turbo_method: "delete", confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="text-center mx-auto">
      <p class="opacity-50 text-center">No products yet.</p>
    </div>
  <% end %>
  </div>
</div>

<%= link_to products_path, class: 'btn btn-link' do %>
  <svg class="close-button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40">
    <defs>
      <style>
        .cls-1 {
          fill: #000;
          stroke-width: 0px;
        }

        .cls-2 {
          fill: none;
          stroke: #000;
          stroke-linecap: round;
          stroke-miterlimit: 10;
          stroke-width: 2px;
        }
      </style>
    </defs>
    <g id="Layer_1-2" data-name="Layer 1">
      <g id="nav-bar">
        <g id="btn_edit" data-name="btn edit">
          <path class="cls-1" d="M20,2c9.93,0,18,8.07,18,18s-8.07,18-18,18S2,29.93,2,20,10.07,2,20,2M20,0C8.95,0,0,8.95,0,20s8.95,20,20,20,20-8.95,20-20S31.05,0,20,0h0Z"/>
          <line class="cls-2" x1="11.36" y1="11.37" x2="28.44" y2="28.57"/>
          <line class="cls-2" x1="28.5" y1="11.43" x2="11.3" y2="28.51"/>
        </g>
      </g>
    </g>
  </svg>
<% end %>