config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root "products#index"

  get "dashboard", to: "dashboards#dashboard"
  get "dashboard/sent", to: "dashboards#sent"
  patch "dashboard/:id/accepted_offer", to: "dashboards#accepted_offer", as: "accepted"
  patch "dashboard/:id/declined_offer", to: "dashboards#declined_offer", as: "declined"
  get "dashboard/received", to: "dashboards#received"
  get "dashboard/finished", to: "dashboards#finished"
  post "dashboard/offer/createCounterOffer", to: "offers#create_counter_offer", as: "counter_offer"

  get "/profile", to: "profiles#profile", as: :my_profile
  patch "/profile", to: "profiles#update", as: :profile

  delete "/product_wishlists/:id", to: "product_wishlists#unheart_wishlist_product", as: :unheart_wishlist_product

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :product_wishlists, only: [:create]
    resources :offers, only: [:create]
  end

  resources :offer_products, only: [:index]
  resources :messages, only: [:index, :show, :new, :create, :destroy]
  resources :offers, only: [:index, :show, :destroy]
  resources :profiles, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :categories, only: [:index]
  resources :product_wishlists, only: [:destroy]
  resources :wishlists, only: [:show]

  resources :products do
    post 'toggle_favorite', on: :member
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    @sent_offers = current_user.sent_offers
    @received_offers = current_user.received_offers
  end

  # list of offers current user sent
  def sent
    # @offer_products = OfferProduct.joins(:product, :offer)
    #                               .where(offer: { user_sender: current_user })
    @my_offers = Offer.where(user_sender: current_user)

    ##### better to have a direct query for the product
  end

  # current user can delete sent offers
  def destroyOfferProduct
    @offer_product = Offer_product.find(params[:id])
  end

  # received offers from other users to current user
  def received
    @received_offers_unfiltered = Offer.where(user_receiver_id: current_user.id)

    # Step 2: Get the offer_ids that appear more than once in OfferProduct
    offer_ids_with_multiple_products = OfferProduct
      .group(:offer_id)
      .having('COUNT(*) > 1')
      .pluck(:offer_id)

    # Step 3: Filter out the offers that have these offer_ids
    @received_offers = @received_offers_unfiltered
    .where.not(id: offer_ids_with_multiple_products).and(@received_offers_unfiltered.where.not(status: "declined"))
    @new_offer = Offer.new
  end

  def finished
    # reversed logic of receive
    @received_offers_1 = Offer.where(user_receiver_id: current_user.id).or(Offer.where(user_sender_id: current_user.id))

    offer_ids_with_multiple_products = OfferProduct
    .group(:offer_id)
    .having('COUNT(*) > 1')
    .pluck(:offer_id)

    @received_offers = @received_offers_1
      .where(id: offer_ids_with_multiple_products).or(@received_offers_1.where(status: "declined"))

    @received_offers.uniq(&:products)
    # the same as receivef but with sender

    @received_offers = @received_offers.sort_by(&:created_at).reverse
  end

   # current user must select from other´s users items
  def select
    @offer_products = Offer_product.all
  end

  # current user sends confirmation
  def confirmRecieved
    @offer_products = Offer_product.all
  end

  #  current user can delete received offer
  def destroyRecieved
    @offer_product = Offer_product.find(params[:id])
  end


  # confirmation of sent offer with received offer
  def match
    @offer_products= Offer_product.all
    @products.current_user = Product.find(params[:current_user])
  end

  def destroyMatch

  end

  # users can chat after Match
  def chat
  end

  def accepted_offer
    @offer = Offer.find(params[:id])
    @offer.accepted!
    redirect_to dashboard_finished_path
  end

  def declined_offer
    @offer = Offer.find(params[:id])
    @offer.declined!
    redirect_to dashboard_finished_path
  end

end

app/views/dashboards/dashboard.html.erb
<div class="container-full">
  <div>
    <img src="<%= current_user.avatar %>" alt="Profile Picture" class="profile-picture">
  </div>
  <div class="container-greetings">
    <h1>Hello, <%= current_user.first_name %></h1>
  </div>
  <div class="container-greetings-message">
    <h4>Your Dashboard</h4>
  </div>
  <div class="dashboard-offer-button-container">
    <% if @received_offers.present? %>
      <%= link_to "Received Offer", dashboard_received_path, class: "dashboard-offer-button" %>
    <% else %>
      <%= link_to "Received Offer", "#", class: "dashboard-offer-button disabled", disabled: true %>
    <% end %>
  </div>
  <div class="wishlist-container">
    <% if @received_offers.present? %>
      <% @received_offers.each do |offer| %>
        <% if offer.products %>
          <% offer.products.each do |product| %>
            <% if offer.status=="pending"%>
              <div class="dashboard-product-card">
                <%= link_to product_path(product) , class: "text-decoration-none" do %>
                  <div class="wishlist-product-image">
                    <%= cl_image_tag product.photo.key, class: 'product-image img-fluid' %>
                  </div>
                  <div class="product-info">
                    <div class="product-title-container">
                      <span class="product-title"><%= truncate(product.title, length: 30, omission: "...") %></span>
                    </div>
                    <div class="product-description-container">
                      <span class="product-description"><%= truncate(product.description, length: 80, omission: "...") %></span>
                    </div>
                  </div>
                <% end %>
                <div class="product-actions">
                  <div class="dashboard-offer-decline-container">
                    <%= link_to "Decline" ,declined_path(offer), data: {"turbo-method": :patch}, class: "delete-icon" ,class: "decline-button decline-button-left-align"  %>
                  </div>
                  <div class="dashboard-offer-accept-container">
                    <%= link_to "Accept", accepted_path(offer), data: {"turbo-method": :patch}, class: "button" ,class: "accept-button accept-button-right-align" %>
                  </div>
                </div>
              </div>
            <%end%>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <div>
        <p>No Received offers found</p>
      </div>
    <% end %>
  </div>
  <div class="dashboard-offer-button-container">
    <% if @sent_offers.present? %>
      <%= link_to "Sent offers", dashboard_sent_path, class: "dashboard-offer-button" %>
    <% else %>
      <%= link_to "Sent offers", "#", class: "dashboard-offer-button disabled", disabled: true %>
    <% end %>
  </div>
  <div class="wishlist-container">
    <% if @sent_offers.present? %>
      <% @sent_offers.each do |offer| %>
        <% if offer.products %>
          <% offer.products.each do |product| %>
            <div class="dashboard-product-card">
              <%= link_to product_path(product) , class: "text-decoration-none" do %>
                <div class="wishlist-product-image">
                  <%= cl_image_tag product.photo.key, class: 'product-image img-fluid' %>
                </div>
                <div class="product-info">
                  <div class="product-title-container">
                    <span class="product-title"><%= truncate(product.title, length: 30, omission: "...") %></span>
                  </div>
                  <div class="product-description-container">
                    <span class="product-description"><%= truncate(product.description, length: 80, omission: "...") %></span>
                  </div>
                </div>
              <% end %>
              <div class="product-actions">
                <div class="dashboard-product-delete-button-container">
                  <%= link_to image_tag("icons/btn Trash.svg", style: "width: 25px") , user_offer_path(current_user, offer), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Sure?"}  %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <div>
        <p>No Sent offers found</p>
      </div>
    <% end %>
  </div>
  <div class="dashboard-offer-button-container">
    <% if @received_offers.present? %>
      <%= link_to "Finished Deals", dashboard_finished_path, class: "dashboard-offer-button" %>
    <% else %>
      <%= link_to "Finished Deals", "#", class: "dashboard-offer-button disabled", disabled: true %>
    <% end %>
  </div>
  <div class="wishlist-container">
    <% if @received_offers.present? %>
      <% @received_offers.each do |offer| %>
        <% if offer.products %>
          <% offer.products.each do |product| %>
            <% if offer.status!="pending"%>
              <div class="dashboard-product-card">
                <%= link_to product_path(product) , class: "text-decoration-none" do %>
                  <div class="wishlist-product-image">
                    <%= cl_image_tag product.photo.key, class: 'product-image img-fluid' %>
                  </div>
                  <div class="product-info">
                    <div class="product-title-container">
                      <span class="product-title"><%= truncate(product.title, length: 30, omission: "...") %></span>
                    </div>
                  </div>
                <% end %>
                <div>
                  <%if offer.status=="declined"%>
                    <div class="offer-status-container">
                      <span> Offer Declined</span>
                    </div>
                    <div class="product-actions d-flex justify-content-center">
                      <div class="dashboard-offer-accept-container d-flex justify-content-center">
                        <%= link_to "Accept", accepted_path(offer), data: {"turbo-method": :patch}, class: "button" ,class: "accept-button " %>
                      </div>
                    </div>
                  <%end%>
                  <%if offer.status=="accepted"%>
                    <div class="offer-status-container">
                      <span> Offer Accepted</span>
                    </div>
                    <div class="product-actions d-flex justify-content-center">
                      <div class="dashboard-offer-decline-container d-flex justify-content-center">
                        <%= link_to "Decline" ,declined_path(offer), data: {"turbo-method": :patch}, class: "delete-icon" ,class: "decline-button "  %>
                      </div>
                    </div>
                  <%end%>
                </div>
              </div>
            <%end%>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <div>
        <p>There are no Completed Offers Found!</p>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/finished.html.erb
<div class="fixed-top-container">
  <div >
    <%= link_to '⬅️ Back', 'javascript:history.back()' , class: "back-button"%>
  </div>
</div>
<div class="container-full">
  <div >
    <div >
      <h1>Last exchanges </h1>
    </div>
    <div >
      <% @received_offers.each do |offer| %>
        <% next if offer.products.empty? %>
        <% their_product = offer.products.first.title %>
        <% counter_offer_product = offer.products.second&.title %>
        <% other_user = User.find(offer.user_receiver_id) %>
        <div>
          <h2> <%= counter_offer_product %> X  <%= their_product %> </h2>
          <h3>Status: <%= offer.status&.capitalize %></h3>
          <% if offer.accepted?%>
            <%= link_to "Send message", messages_path, class: "button"  %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboards/received.html.erb
<div class="fixed-top-container">
  <div >
    <%= link_to '⬅️ Back', 'javascript:history.back()' , class: "back-button"%>
  </div>
</div>
<div class="container-full">
  <div class="container-greetings">
    <h1>Hello, <%= current_user.first_name %></h1>
  </div>
  <div >
    <h3> Received Offers</h3>
  </div>
  <% @received_offers.each do |offer| %>
    <% offer.products.each do |product| %>
      <% other_user = User.find(offer.user_sender_id) %>
      <div class="greetings-text">
        <h3>Hey!<%= other_user.first_name %> matched <%= product.title %></h3>
      </div>
      <div class="product-photoinfo-container">
        <div class="zhaopian-container">
          <div class="product-image-container">
            <%= cl_image_tag product.photo.key, class: 'product-image img-fluid' %>
          </div>
        </div>
        <div class="offer-deal-description-container">
          <div class="product-title-container">
            <span class="product-title"><%= truncate(product.title, length: 30, omission: "...") %></span>
          </div>
          <div class="product-description-container">
            <span class="product-description"><%= truncate(product.description, length: 80, omission: "...") %></span>
          </div>
        </div>
      </div>
      <div class="another-user-text">
        <h3>Check <%= other_user.first_name %>´s items list!</h3>
      </div>
      <div class="product-name-recieved-container">
        <form action="offer/createCounterOffer" method="post" class="form-offer">
          <input type="hidden" name="offer[my_product]" value="<%= product.id %>">
          <input type="hidden" name="offer[offer_id]" value="<%= offer.id %>">
          <div class="recieved-user-itemlist-container">
            <div class="zhaopian2-container">
              <div class="container-radio">
                <ul>
                  <% other_user.products.each do |product| %>
                    <li>
                      <div class="info-list-container d-flex justify-content-between">
                        <div class="d-flex align-items-center gap-2">
                          <input type="radio" id="product_<%= product.id %>" name="offer[their_product]" value="<%= product.id %>">
                          <label for="product_<%= product.id %>"><%= product.title %></label>
                        </div>
                        <%= cl_image_tag product.photo.key, class: 'received-product-image img-fluid' %>
                      </div>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
          <div class="recieved-button-container">
            <button type="submit">Make an offer</button>
            <%= link_to "Decline", declined_path(offer), data: {"turbo-method": :patch}, class: "button" %>
          </div>
        </form>
      </div>
    <% end %>
  <% end %>
</div>

app/views/dashboards/sent.html.erb
<div class="fixed-top-container">
  <div >
    <%= link_to '⬅️ Back', 'javascript:history.back()' , class: "back-button"%>
  </div>
</div>
<div class="container-full">
  <div class="container-greetings">
    <h1>Hello, <%= current_user.first_name %></h1>
  </div>
  <div class="sent-offer-container">
    <% @my_offers.each do |offer| %>
      <% receiver = User.find(offer.user_receiver_id) %>
      <% if offer.products.present?%>
        <% their_product = offer.products.first.title %>
        <div class="card">
          <div class="card-content">
            <div>
              <div>
                <p>You are interested in <%= receiver.first_name %>'s <%= their_product %></p>
              </div>
              <div>
                <%= link_to image_tag("icons/btn Trash.svg", style: "width: 25px") , user_offer_path(current_user, offer), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Sure?", redirect_to: request.original_url}  %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>