config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root "products#index"

  get "dashboard", to: "dashboards#dashboard"
  get "dashboard/sent", to: "dashboards#sent"
  patch "dashboard/:id/accepted_offer", to: "dashboards#accepted_offer", as: "accepted"
  patch "dashboard/:id/declined_offer", to: "dashboards#declined_offer", as: "declined"
  get "dashboard/received", to: "dashboards#received"
  get "dashboard/finished", to: "dashboards#finished"
  post "dashboard/offer/createCounterOffer", to: "offers#create_counter_offer", as: "counter_offer"

  get "/profile", to: "profiles#profile", as: :my_profile
  patch "/profile", to: "profiles#update", as: :profile

  delete "/product_wishlists/:id", to: "product_wishlists#unheart_wishlist_product", as: :unheart_wishlist_product

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :product_wishlists, only: [:create]
    resources :offers, only: [:create]
  end

  resources :offer_products, only: [:index]
  resources :messages, only: [:index, :show, :new, :create, :destroy]
  resources :offers, only: [:index, :show, :destroy]
  resources :profiles, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :categories, only: [:index]
  resources :product_wishlists, only: [:destroy]
  resources :wishlists, only: [:show]

  resources :products do
    post 'toggle_favorite', on: :member
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :product_wishlists, dependent: :destroy
  has_many :products, through: :product_wishlists
  #has_many :products, dependent: :destroy
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def show
    @wishlist = current_user.wishlist
  end

  def destroy
    @product_wishlist = Product_wishlist.find(params[:id])
    @product_wishlist.destroy
    redirect_to wishlist_path(current_user.wishlist.id)
  end
end

app/views/wishlists/show.html.erb
<div class="container-full">
  <div>
    <h1>Hello, <%= current_user.first_name %></h1>
  </div>
  <div class="container-greetings-message">
    <h4>Your Wishlist</h4>
  </div>

  <div class="wishlist-container">
    <% @wishlist.products.each do |product| %>
      <div class="wishlist-card">
        <div class="wishlist-product-image product-background">
          <%= cl_image_tag product.photo.key, class: 'product-image img-fluid' %>
        </div>
        <div class="product-info">
          <div class="product-title-container">
            <span class="product-title"><%= truncate(product.title, length: 30, omission: "...") %></span>
          </div>
          <div class="product-description-container">
            <span class="product-description"><%= truncate(product.description, length: 20, omission: "...") %></span>
          </div>
          <div class="product-actions">
            <div class="wishlist-send-and-offer-button">
              <%= link_to "Offer", product_offers_path(product), data: {turbo_method: :post}, class: "user-button" %>
            </div>
            <div class="delete-button">
              <% product_wishlist = current_user.wishlist.product_wishlists.find_by(product_id: product.id) %>
              <%= link_to image_tag("icons/btn Trash.svg", style: "width: 25px"), product_wishlist_path(product_wishlist.id), style: "width:100px", data: {turbo_method: :delete, turbo_confirm: "Sure?"} %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to products_path, class: 'btn btn-link' do %>
  <svg class="close-button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40">
    <defs>
      <style>
        .cls-1 {
          fill: #000;
          stroke-width: 0px;
        }

        .cls-2 {
          fill: none;
          stroke: #000;
          stroke-linecap: round;
          stroke-miterlimit: 10;
          stroke-width: 2px;
        }
      </style>
    </defs>
    <g id="Layer_1-2" data-name="Layer 1">
      <g id="nav-bar">
        <g id="btn_edit" data-name="btn edit">
          <path class="cls-1" d="M20,2c9.93,0,18,8.07,18,18s-8.07,18-18,18S2,29.93,2,20,10.07,2,20,2M20,0C8.95,0,0,8.95,0,20s8.95,20,20,20,20-8.95,20-20S31.05,0,20,0h0Z"/>
          <line class="cls-2" x1="11.36" y1="11.37" x2="28.44" y2="28.57"/>
          <line class="cls-2" x1="28.5" y1="11.43" x2="11.3" y2="28.51"/>
        </g>
      </g>
    </g>
  </svg>
<% end %>