config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root "products#index"

  get "dashboard", to: "dashboards#dashboard"
  get "dashboard/sent", to: "dashboards#sent"
  patch "dashboard/:id/accepted_offer", to: "dashboards#accepted_offer", as: "accepted"
  patch "dashboard/:id/declined_offer", to: "dashboards#declined_offer", as: "declined"
  get "dashboard/received", to: "dashboards#received"
  get "dashboard/finished", to: "dashboards#finished"
  post "dashboard/offer/createCounterOffer", to: "offers#create_counter_offer", as: "counter_offer"

  get "/profile", to: "profiles#profile", as: :my_profile
  patch "/profile", to: "profiles#update", as: :profile

  delete "/product_wishlists/:id", to: "product_wishlists#unheart_wishlist_product", as: :unheart_wishlist_product

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :product_wishlists, only: [:create]
    resources :offers, only: [:create]
  end

  resources :offer_products, only: [:index]
  resources :messages, only: [:index, :show, :new, :create, :destroy]
  resources :offers, only: [:index, :show, :destroy]
  resources :profiles, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :categories, only: [:index]
  resources :product_wishlists, only: [:destroy]
  resources :wishlists, only: [:show]

  resources :products do
    post 'toggle_favorite', on: :member
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :photo
  has_many :offer_products, dependent: :destroy
  belongs_to :wishlist, optional: true
  has_many :product_wishlists, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @categories = Category.all
    if params[:category].present?
      @products = Product.where.not(user: current_user).where(category_id: params[:category])
    else
      @products = Product.where.not(user: current_user)
    end
  end

  def show
    @product = Product.find(params[:id])
    #//@wishlist = Wishlist.find(params[:id])
  end

  def new
    @product = Product.new
    @categories = Category.new
  end

  def create
    @product = Product.create(product_params)
    @product.user = current_user
    if @product.save
      redirect_to my_profile_path(@user)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    user = User.find(params[:user_id])
    product = user.products.find(params[:id])
    offer_product = OfferProduct.where(product_id: product.id)
    offer_product.destroy_all
    product.destroy
    redirect_to request.referer
  end

  def toggle_favorite
    @product = Product.find(params[:id])
    if current_user.wishlist.include?(@product)
      current_user.wishlist.delete(@product)
      favorited = false
    else
      current_user.wishlist << @product
      favorited = true
    end

    if current_user.save
      render json: { success: true, favorited: favorited }
    else
      render json: { success: false }, status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :photo, :category_id, :description, :condition, :price)
  end
end

app/views/products/edit.html.erb
<div class="login-container">
  <div class="login-box">
    <%= simple_form_for(@product, url: product_path, method: :patch) do |f| %>
      <%= f.input :title %>
      <%= f.input :category %>
      <%= f.input :description %>
      <%= f.input :condition %>
      <%= f.input :price %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-full container-full-fixed">
  <div class="container-greetings">
    <h1>Hello, <%= current_user.first_name %></h1>
    <div class="container-greetings-message">
      <h4>Ready to circle today?</h4>
    </div>
  </div>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Categories
    </button>
    <ul class="dropdown-menu" aria-labelledby="categoryDropdown">
      <% @categories.each do |category| %>
        <li><%= link_to category.name, products_path(category: category.id), class: "dropdown-item" %></li>
      <% end %>
    </ul>
  </div>
  <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% if @products.empty? %>
        <div class="carousel-item active">
          <p>No products yet!</p>
        </div>
      <% else %>
        <% @products.each_with_index do |product, index| %>
          <div class="carousel-item <%= 'active' if index == 0 %>">
            <div class="container-white position-relative">
              <% if current_user.wishlist.products.include?(product) %>
                <% product_wishlist = current_user.wishlist.product_wishlists.find_by(product_id: product.id) %>
                <%= link_to unheart_wishlist_product_path(product_wishlist.id), data: { turbo_method: :delete }, class: 'favorite-btn' do %>
                  <%= image_tag 'heart_icon_red', class: 'red-favorite-btn' %>
                <% end %>
              <% else %>
                <%= link_to product_product_wishlists_path(product.id), data: { turbo_method: :post }, class: 'favorite-btn' do %>
                  <%= image_tag 'heart_icon_gray', alt: 'Add to favorite', class: 'favorite-icon' %>
                <% end %>
              <% end %>
              <%= link_to product_path(product) , class: "text-decoration-none" do %>
                <div class="product-image-container">
                  <% if product.photo.key.present? %>
                    <%= cl_image_tag product.photo.key, class: 'product-image img-fluid' %>
                  <% else %>
                    <%= image_tag "default_product.jpg", class: 'product-image img-fluid' %>
                  <% end %>
                </div>
                <div class="product-title-container">
                  <span class="product-title"><%= truncate(product.title, length: 30, omission: "...") %></span>
                </div>
                <div class="product-description-container">
                  <span class="product-description"><%= truncate(product.description, length: 80, omission: "...") %></span>
                </div>
              <%end%>
              <div class="send-offer-button-container">
                <%= link_to "Send an offer", product_offers_path(product), data: {turbo_method: :post}, class: "user-button" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</button>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="product-submit-page">
    <div>
      <h1 class="dark-gray-text">Add Your Item!</h1>
    </div>
    <div>
      <form id="productForm" class="dark-gray-text" action="/products" method="post" enctype="multipart/form-data">
        <div class="styled-input">
          <input type="text" id="title" name="product[title]" placeholder="Title">
        </div>
        <div class="styled-input">
          <select id="category_id" name="product[category_id]" class="narrow-dropdown-categories">
            <% Category.all.each do |category| %>
              <option value="<%= category.id %>"><%= category.name %></option>
            <% end %>
          </select>
        </div>
        <div class="styled-input">
          <select id="condition" name="product[condition]">
            <option value="New">New</option>
            <option value="Used">Used</option>
            <option value="Refurbished">Refurbished</option>
          </select>
        </div>
        <div class="styled-input">
          <input type="number" id="price" name="product[price]" placeholder="Price">
        </div>
        <div class="styled-input">
          <textarea id="description" name="product[description]" rows="5" placeholder="Description"></textarea>
        </div>
        <div class="styled-input">
          <input type="file" id="photo" name="product[photo]" class="circle-input">
        </div>
        <div class="styled-input">
          <button type="submit" class="submit-button">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
  document.getElementById('productForm').addEventListener('submit', function(event) {
    var title = document.getElementById('title').value;
    var category = document.getElementById('category_id').value;
    var condition = document.getElementById('condition').value;
    var price = document.getElementById('price').value;
    var description = document.getElementById('description').value;
    var photo = document.getElementById('photo').value;

    if (!title || !category || !condition || !price || !description || !photo) {
      alert('Please fill in all fields.');
      event.preventDefault(); // Prevent form submission
    }
  });
</script>

app/views/products/show.erb
<h1> HELLO, PRODUCT SHOW </h1>

app/views/products/show.html.erb
<div class="container-full mb-5">
  <div class="product-details">
    <div class="picstogether"> 
      <%= image_tag @product.user.avatar, height: 72, width: 72,  crop: :fill, class: "profile-pic m-3" %>
      <%= cl_image_tag @product.photo.key, height: 300, width: 300, crop: :fill, class:"show-pic", style: "border-radius: 20px;"%>
    </div>

    <h1 class="mt-3"><strong><%= @product.title %></strong></h1>

    <p><strong>Owner:</strong><br>
      <%= @product.user.first_name %></p>
    <p><strong>Category:</strong><br>
      <%= @product.category.name %></p>
    <p><strong>Description:</strong><br>
      <%= truncate(@product.description, length: 170, omission: '...') %></p>
    <p><strong>Condition:</strong><br>
      <%= @product.condition %></p>
    <p><strong>Price:</strong><br>
      <%= number_to_currency(@product.price, unit: "€", precision: 0) %> ~ <%= number_to_currency(@product.price, unit: "€", precision: 0) %></p>

    <div class="product-actions">
      <%= link_to 'Back to Products', products_path, class: 'btn btn-link' %>
    </div>

  <%= link_to products_path, class: 'btn btn-link' do %>
    <svg class="close-button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40">
      <defs>
        <style>
          .cls-1 {
            fill: #000;
            stroke-width: 0px;
          }

          .cls-2 {
            fill: none;
            stroke: #000;
            stroke-linecap: round;
            stroke-miterlimit: 10;
            stroke-width: 2px;
          }
        </style>
      </defs>
      <g id="Layer_1-2" data-name="Layer 1">
        <g id="nav-bar">
          <g id="btn_edit" data-name="btn edit">
            <path class="cls-1" d="M20,2c9.93,0,18,8.07,18,18s-8.07,18-18,18S2,29.93,2,20,10.07,2,20,2M20,0C8.95,0,0,8.95,0,20s8.95,20,20,20,20-8.95,20-20S31.05,0,20,0h0Z"/>
            <line class="cls-2" x1="11.36" y1="11.37" x2="28.44" y2="28.57"/>
            <line class="cls-2" x1="28.5" y1="11.43" x2="11.3" y2="28.51"/>
          </g>
        </g>
      </g>
    </svg>
  </div>
  <% end %>
</div>

app/views/products/usersselect.html.erb
<input name="whishlist[]" type="checkbox">  Football